version: "3"
services:
    web:
        image: mrx-nginx-php
        build: .
        restart: always
        volumes:
            - ./code:/var/www
            - ./code/public:/var/www/html
        ports:
            - "8181:80"
        networks:
            myNetwork:
                ipv4_address: 172.16.99.10
       
    php-fpm:
        build: install/php-fpm
        ports:
            - 9010:9000
        volumes:
            - ./code:/var/www/html/
        links:
            - db
    nginx:
        build: install/nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
    db:
        image: mysql:5.6
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: MyDB
            MYSQL_USER: MyDB
            MYSQL_PASSWORD: rootpassword
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - MysqlVolume:/var/lib/mysql
        networks:
            myNetwork:
                ipv4_address: 172.16.99.11
                

networks:
    myNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.99.0/24
volumes:
  MysqlVolume:
